name: 'Execução dos testes'

on:
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: 'Clonando código do repositório'
        uses: actions/checkout@v4
      - name: 'Instalando Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: 'Instalando Yarn'
        run: npm install -g yarn

      - name: 'Instalando dependências do projeto'
        run: yarn install
      - name: Executando testes
        run: npx mocha Testes/01-testes.js
      
      - name: Executando testes do trabalho final de JS
        run: npx mocha trabalho/trabalho-final/trabalho-final.js