name: 'Execução dos testes'

on:
  workflow_dispatch:

jobs:
  Testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Instalando Mocha
        run: npm install -D mocha
      - name: Executando testes
        run: npx mocha Testes/01-testes.js
